# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               regularcoder
tagline:             'A rising tide lifts all boats'
description:         'A personal blog on things that interest me'
url:                 http://regularcoder.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              regularcoder
  url:               http://regularcoder.github.io
  email:             regularcoder@gmail.com

# Custom vars
version:             1.0.0

gems:				[jekyll-paginate]
