# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               regularcoder
tagline:             'A rising tide lifts all boats'
description:         'A blog on programming, reading, writing and traveling'
url:                 http://localhost:4000
baseurl:             /
paginate:            10
excerpt_separator:   <!--more-->
# About/contact
author:
  name:              regularcoder
  url:               http://regularcoder.github.io
  email:             regularcoder@gmail.com

# Custom vars
version:             1.0.0

gems:				[jekyll-paginate]
